In [1]:
from sklearn.datasets import load_iris
from scipy import stats

import pandas as pd
import numpy as np

# Estatística I

## Amostragem

In [2]:
iris = pd.DataFrame(load_iris().data)
iris.insert(4, "class", load_iris().target)
iris

0    1    2    3  class
0    5.1  3.5  1.4  0.2      0
1    4.9  3.0  1.4  0.2      0
2    4.7  3.2  1.3  0.2      0
3    4.6  3.1  1.5  0.2      0
4    5.0  3.6  1.4  0.2      0
..   ...  ...  ...  ...    ...
145  6.7  3.0  5.2  2.3      2
146  6.3  2.5  5.0  1.9      2
147  6.5  3.0  5.2  2.0      2
148  6.2  3.4  5.4  2.3      2
149  5.9  3.0  5.1  1.8      2

[150 rows x 5 columns]

In [3]:
amostra_aleatoria_simples = np.random.choice(a = (0, 1),
                           p = (0.5, 0.5),
                          size = 150,
                          replace = True)

amostra_aleatoria_simples

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0])

## Variância e centralidade

In [4]:
arr = np.array([int(np.random.random() * 100)
    for i in range(20)
])

arr

array([99, 23, 52, 58, 14,  5, 82, 48, 98, 93, 98, 61, 56, 98,  0, 55, 44,
       80, 37,  3])

### Média, mediana e moda

In [5]:
print(arr.mean()) # média
print(np.median(arr)) # mediana
print(stats.mode(arr)) # moda

55.2
55.5
ModeResult(mode=array([98]), count=array([3]))


### Quartis

In [6]:
quartis = np.quantile(arr, (
    0.25, 0.5, 0.75
)) # cria-se uma variável composta para colocar os Quartis desejados

quartis

array([33.5 , 55.5 , 84.75])

### Desvio padrão e variância

In [7]:
desvio_padrao = np.std(arr, ddof = 1)
variancia = desvio_padrao ** 2

print(desvio_padrao)
print(variancia)

33.84422519348565
1145.4315789473687


In [8]:
stats.describe(arr)

DescribeResult(nobs=20, minmax=(0, 99), mean=55.2, variance=1145.4315789473685, skewness=-0.19519767242362154, kurtosis=-1.1492724723205878)

## Distribuição

### Distribuição binomial

In [20]:
# Se eu jogar uma moeda 5 vezes, qual a probabilidade de cair 3 caras?
# n = 5; k = 3; sucesso = 1/2 ou 0.5

n = 5
k = 3
prob = 0.5

stats.binom.pmf(k, n, prob)

0.3125