In [1]:
from sklearn.datasets import load_iris
from scipy import stats

import pandas as pd
import numpy as np

# Estatística I

## Amostragem

In [2]:
iris = pd.DataFrame(load_iris().data)
iris.insert(4, "class", load_iris().target)
iris

0    1    2    3  class
0    5.1  3.5  1.4  0.2      0
1    4.9  3.0  1.4  0.2      0
2    4.7  3.2  1.3  0.2      0
3    4.6  3.1  1.5  0.2      0
4    5.0  3.6  1.4  0.2      0
..   ...  ...  ...  ...    ...
145  6.7  3.0  5.2  2.3      2
146  6.3  2.5  5.0  1.9      2
147  6.5  3.0  5.2  2.0      2
148  6.2  3.4  5.4  2.3      2
149  5.9  3.0  5.1  1.8      2

[150 rows x 5 columns]

In [3]:
amostra_aleatoria_simples = np.random.choice(a = (0, 1),
                           p = (0.5, 0.5),
                          size = 150,
                          replace = True)

amostra_aleatoria_simples

array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0])

## Variância e centralidade

In [4]:
arr = np.array([int(np.random.random() * 100)
    for i in range(20)
])

arr

array([62, 17, 43, 45, 49, 67, 67, 46, 43, 22,  3, 30, 47,  0, 35, 42,  0,
       49, 39, 55])

### Média, mediana e moda

In [5]:
print(arr.mean()) # média
print(np.median(arr)) # mediana
print(stats.mode(arr)) # moda

38.05
43.0
ModeResult(mode=array([0]), count=array([2]))


### Quartis

In [6]:
quartis = np.quantile(arr, (
    0.25, 0.5, 0.75
)) # cria-se uma variável composta para colocar os Quartis desejados

quartis

array([28., 43., 49.])

### Desvio padrão e variância

In [7]:
desvio_padrao = np.std(arr, ddof = 1)
variancia = desvio_padrao ** 2

print(desvio_padrao)
print(variancia)

20.433396296517284
417.52368421052626


In [8]:
stats.describe(arr)

DescribeResult(nobs=20, minmax=(0, 67), mean=38.05, variance=417.5236842105263, skewness=-0.6052743735307787, kurtosis=-0.5122857545012773)

## Distribuição

### Distribuição binomial

In [9]:
# Se eu jogar uma moeda 5 vezes, qual a probabilidade de cair 3 caras?
# n = 5; k = 3; sucesso = 1/2 ou 0.5

n = 5
k = 3
prob = 0.5

stats.binom.pmf(k, n, prob)

0.3125

### Distribuição normal

In [10]:
"""
Os objetos de uma cesta tem média 8 e dp 2.
Qual a probabilidade deu tirar um objeto < 6kg?
"""

norm = stats.norm
norm.cdf(6, 8, 2) # peso; média; dp 

0.15865525393145707

In [11]:
# Qual a probabilidade deu tirar um objeto > 6kg?

norm.sf(6, 8, 2) # peso; média; dp

0.8413447460685429

In [12]:
# Probabilidade do peso ser > 6kg ou < 10kg

norm.cdf(6, 8, 2) + norm.sf(10, 8, 2)

0.31731050786291415

### Distribuição T de Student

In [15]:
# um conjunto de cientistas de dados foram entrevistas e chegou ao resultado de 75 reais por hora
# amostra = 9
# probabilidade de um cientista selecionado ganhar < 75 por hora e depois de ganhar > 75 por h

print(stats.t.cdf(1.5, 9)) # < 75
print(stats.t.sf(1.5, 9)) # > 75

0.9160746719714626
0.08392532802853743
