# Numpy


#### "NumPy é um pacote para a linguagem Python que suporta arrays e matrizes multidimensionais, 
#### possuindo uma larga coleção de funções matemáticas para trabalhar com estas estruturas." - Wikipedia


In [1]:
import numpy as np

## Basíco do Numpy
#### Me guiei pelo tutorial do Keith Galli, o qual o vídeo se encontra neste link: https://www.youtube.com/watch?v=GB9ByFAIAH4

In [8]:
array = np.array([
    [i for i in range(5)] for x in range(5)]

, dtype = "int16") # criando um array numPy array

In [3]:
# retornando o número de dimensões
np.ndim(array)
array.ndim

2

In [4]:
# pegando a quantidade linhas e colunas
array.shape

(5, 5)

In [9]:
# pegar um elemento especifico array[row, column]

array[0, 0] # pega o primeiro número da linha 0
array[:2, 0] # pega os dois primeiros das linhas 0 e 1
array[:, :2] # pega os 2 primeiros números de todas as linhas

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]], dtype=int16)

In [13]:
# mudar elementos

array[:, 3] = 10 # troca a coluna 3 de todas as linhas por 10
array[0, 3] = 5  # troca a coluna 3 da primeira linha por 5
array

array([[ 0,  1,  2,  5,  4],
       [ 0,  1,  2, 10,  4],
       [ 0,  1,  2, 10,  4],
       [ 0,  1,  2, 10,  4],
       [ 0,  1,  2, 10,  4]], dtype=int16)

## Tipos de Arrays do Numpy

In [15]:
zeros = np.zeros((2, 3)) # array com zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
uns = np.ones((2, 3)) # array com uns
uns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# array com qualquer numero

array = np.full((2, 3), 20)
array

array([[20, 20, 20],
       [20, 20, 20]])

In [20]:
# array com números decimais aleatorios

random_numbers = np.random.rand(2,3)
random_numbers

array([[0.42631129, 0.75099141, 0.5282752 ],
       [0.93810593, 0.31574208, 0.94295571]])

In [28]:
# array com números inteiros aleatorios

random_numbers_integer = np.random.randint(-4, 40, size = (2,3))
random_numbers_integer

array([[ 1,  8, 10],
       [10, 26, 23]])

In [30]:
# matriz identidade

matriz_identidade = np.identity(3)
matriz_identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# repetir elementos de um array

arr = np.array([[1, 2, 3]])
repeate = np.repeat(arr, 2, axis = 0)
repeate

array([[1, 2, 3],
       [1, 2, 3]])

In [38]:
"""
1 1 1 1 1 
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1

Objetivo: tentar gerar essa matriz
"""

arr = np.ones((5,5))
arr[1:4, 1:4] = 0
arr[2, 2] = 9
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Como copiar corretamente um array?

arrA = np.array([1, 2, 3])
arrB = arrA.copy()
arrB[0] = 0
print(arrA, arrB)

[1 2 3] [0 2 3]


## Matemática

In [41]:
array = np.array([1, 2, 3, 4])
array

array([1, 2, 3, 4])

In [43]:
array + 2

array([3, 4, 5, 6])

In [44]:
array - 2

array([-1,  0,  1,  2])

In [45]:
array * 2

array([2, 4, 6, 8])

In [46]:
array / 2

array([0.5, 1. , 1.5, 2. ])

In [51]:
# seno, cosseno e tangente

sin = np.sin(array)
cos = np.cos(array)
tg = np.tan(array)

print(sin, cos, tg)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ] [ 0.54030231 -0.41614684 -0.9899925  -0.65364362] [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


## Álgebra Linear

In [52]:
a = np.ones((2,3))
b = np.full((3,2), 4)

# a * b = erro, já que as linhas e colunas são diferentes.

np.matmul(a, b)

array([[12., 12.],
       [12., 12.]])

In [53]:
# encontrar a determinante de uma matriz
np.linalg.det(matriz_identidade)

1.0

In [63]:
# matriz inversa

np.linalg.inv([[1, 2], [3, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [64]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

## Estatística

In [69]:
arr_est = np.array([[1, 2, 3], [4, 5, 6]])


print(arr_est.min())
print(arr_est.max())
print(arr_est.sum())

1
6
21


## Reorganização de Arrays

In [81]:
antes = np.array([[1,2,3,4], [5, 7, 9, 1]])
print(antes)

depois = antes.reshape((8, 1))
print(depois)

[[1 2 3 4]
 [5 7 9 1]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [7]
 [9]
 [1]]
